
services:
    postgres:
        image: postgres:15.1
        restart: always
        environment:
            POSTGRES_DB: "mypastebin"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "admin"
        ports:
            - "5430:5432"
        volumes:
            - db:/var/lib/postgresql/data
volumes:
    db:
        driver: local