spring:
  profiles:
    active: "dev"

---

spring:
  config:
    activate:
      on-profile: dev

  r2dbc:
    url: r2dbc:postgresql://localhost:5430/mypastebin?schema=public
    password: admin
    username: admin
    pool:
      enabled: true
      initial-size: 2
      max-size: 2
  main:
    web-application-type: reactive
    allow-circular-references: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true
    url: jdbc:postgresql://localhost:5430/mypastebin?schema=public
    user: admin
    password: admin
logging:
  level:
    liquibase: INFO
    web: DEBUG
    org:
      springframework:
        data:
          r2dbc: DEBUG
app:
  all-methods-log:
    enabled: true
springdoc:
  api-docs:
    path: /swagger-doc/v3/api-docs
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
